### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mathesouza** [mathesouza/portfolio-thay#2]
- [ ] Redimensionar uma thumb da arte antes de upar
- [ ] Listar artes no admin - CRUDinho
- [ ] Footer talvez?
- [ ] Na home, smooth scroll
- [ ] About me
- [ ] Jobs
- [ ] Animações
- [ ] Apresentar erros de login
